name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Donner les permissions d'exécution à Gradle
        run: chmod +x ./gradlew
        
      - name: Construire le projet
        run: |
          ./gradlew build # Ou mvn package si tu utilises Maven
      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construire et taguer l'image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/apiazure:latest .
      - name: Pousser l'image sur Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apiazure:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull de l'image Docker depuis Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/apiazure:latest

      - name: Déploiement de l'image Docker sur Azure Web App
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: appaction
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Profil de publication Azure
          images: ${{ secrets.DOCKER_USERNAME }}/apiazure:latest
