name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull de l'image Docker depuis Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/apiazure:latest

      - name: Déploiement de l'image Docker sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: appaction
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Profil de publication Azure
          images: ${{ secrets.DOCKER_USERNAME }}/apiazure:latest
